### ISSUE TITLE
Unnecessary Files

### ISSUE THREAD

**Issue by MCGenius25** [THS-CompSci/WebApp#11]
All right, we can't communicate everyday, so it can't be helped that we might do the same thing or something unnecessary. Index.html, studentPage.html, and TeacherPage.html are all causing an issue. For one thing, we don't need a student page. The website is **only for teachers.** Also, TeacherPage.html and Index.html are **exactly the same.** They're both supposed to be the home page, and one home page is enough. All these files are causing a lot of confusion. I recommend that we delete the student page altogether and one of the home pages (most likely TeacherPage.html because we already styled Index.html).

**Comment by AllegroStudio** [comment]
I agree. This issue also happens with tScript.js and script.js. They seem to be mostly the same thing but tScript.js is more up to date so I'm using that one at the moment.

**Comment by PoldervaartS** [comment]
i agree and will delete TeacherPage.html along with studentPage.html accordingly, but i am not sure about script.js & tScript.js as Santi has made and been messing with both of those

**Comment by AllegroStudio** [comment]
I asked Santi and he told me to delete script.js. So it seems like the problem is solved!
